spring:
  application:
    name: fundtransfer-service
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8301/eureka/
  instance:
    hostname: localhost   
    