spring:
  application:
    name: db-service
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8301/eureka/
  instance:
    hostname: localhost   