spring:
  application:
    name: registry_service

server:
  port: 8301    

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
      
  